PROFILE="$1"
. "$SMOKE_HERE/prelude.sh"
RES="$SMOKE_SHARE"
. "$SMOKE_WORK/fw_modem.sh"
. "$RES/lib.sh"
sms_tool() {
	[ -n "$DEVICE" ] || return 0
	_sti=$(_st_ident_cmd "$@")
	if [ -n "$_sti" ]; then "$SMOKE_BIN/sms_tool" "$@" | _st_drop_ok
	else "$SMOKE_BIN/sms_tool" "$@"; fi
}
DEVICE="$SMOKE_DEV"
_POLL_AM="9-9"
MODEM_PATH="9-9"
STATIC_CACHE="$SMOKE_WORK/tmp/5gmodem/static_smoke"
REGOK=1
REG=1
CSQ=20
CSQ_PER=64
MODE_NUM=7
MODE="LTE"
COPS_MCC=250
COPS_MNC=01
SEC=wan5g
O=""
[ -n "$SMOKE_FIX" ] && [ -f "$SMOKE_FIX/init" ] && . "$SMOKE_FIX/init"
_SAVED_IFS="$IFS"
. "$PROFILE"
IFS="$_SAVED_IFS"
echo "@@SMOKE_MARK@@"
for _v in MODEL TEMP THERM NEIGHBORS ANTPORTS RXDIV FW PROTO CSQ CSQ_PER MODE SSIM NR_IMEI NR_IMSI NR_ICCID \
	LAC_DEC LAC_HEX TAC_DEC TAC_HEX T_HEX T_DEC CID_DEC CID_HEX PCI EARFCN PBAND \
	S1BAND S1PCI S1EARFCN S2BAND S2PCI S2EARFCN S3BAND S3PCI S3EARFCN S4BAND S4PCI S4EARFCN \
	S1STATE S2STATE S3STATE S4STATE S1RSRP S2RSRP S3RSRP S4RSRP S1RSRQ S2RSRQ S3RSRQ S4RSRQ \
	S1SINR S2SINR S3SINR S4SINR S1RSSI S2RSSI S3RSSI S4RSSI RI PMIMO PMOD S1MIMO S1MOD S2MIMO S2MOD \
	S3MIMO S3MOD S4MIMO S4MOD BANDWIDTH ENBID PATHLOSS TXPOWER UECAT CQI VOLTE RSCP MAXDL MAXUL \
	ECIO RSRP RSRQ RSSI SINR BS_DIST; do
	eval "_x=\$$_v"
	printf '%s=%s\n' "$_v" "$(printf '%s' "$_x" | tr '\n' '|')" >> "$SMOKE_VARS"
done
