# Расшифровка кодов +CME ERROR - ОБЩАЯ ТАБЛИЦА.
#
# ЗАЧЕМ. Раньше каждый разбор ошибки жил у себя (smsbridge, 5gmodem.sh,
# quirks, отчёт) и знал десяток кодов; всё прочее пользователь видел голым
# числом - «+CME ERROR: 133» ни о чём не говорит даже нам. Таблица полная
# (коды 3GPP 27.007 плюс расширения), русская для ходовых случаев.
#
# Использование:  . /usr/share/5gmodem/cme.sh; cme_text 133
# Неизвестный код возвращает пустоту - вызывающий сам решает, что писать.

cme_text() {   # $1 - числовой код
	case "$1" in
		0) echo "Phone failure" ;;
		1) echo "No connection to phone" ;;
		2) echo "Phone-adaptor link reserved" ;;
		3) echo "Operation not allowed" ;;
		4) echo "Operation not supported" ;;
		5) echo "PH-SIM PIN required" ;;
		6) echo "PH-FSIM PIN required" ;;
		7) echo "PH-FSIM PUK required" ;;
		8) echo "PH-NET PIN required" ;;
		9) echo "PH-NET PUK required" ;;
		10) echo "SIM not inserted" ;;
		11) echo "SIM PIN required" ;;
		12) echo "SIM PUK required" ;;
		13) echo "SIM failure" ;;
		14) echo "SIM busy" ;;
		15) echo "SIM wrong" ;;
		16) echo "Incorrect password" ;;
		17) echo "SIM PIN2 required" ;;
		18) echo "SIM PUK2 required" ;;
		19) echo "SIM PIN3 required" ;;
		20) echo "Memory full" ;;
		21) echo "Invalid index" ;;
		22) echo "Not found" ;;
		23) echo "Memory failure" ;;
		24) echo "Text string too long" ;;
		25) echo "Invalid characters in text string" ;;
		26) echo "Dial string too long" ;;
		27) echo "Invalid characters in dial string" ;;
		28) echo "No network service" ;;
		29) echo "Network timeout" ;;
		30) echo "No network service" ;;
		31) echo "Network timeout" ;;
		32) echo "Network not allowed - emergency calls only" ;;
		33) echo "Network personalization PIN required" ;;
		34) echo "Network subset personalization PUK required" ;;
		35) echo "Service provider personalization PIN required" ;;
		36) echo "Service provider personalization PUK required" ;;
		37) echo "Corporate personalization PIN required" ;;
		38) echo "Corporate personalization PUK required" ;;
		39) echo "Hidden key required" ;;
		40) echo "PUK required" ;;
		41) echo "PIN required" ;;
		42) echo "PIN2 required" ;;
		43) echo "PUK2 required" ;;
		44) echo "PIN3 required" ;;
		45) echo "PUK3 required" ;;
		46) echo "PIN4 required" ;;
		47) echo "PUK4 required" ;;
		48) echo "EAP authentication failure" ;;
		49) echo "Unknown error" ;;
		50) echo "Incorrect parameters" ;;
		100) echo "Unknown error" ;;
		103) echo "Illegal MS - not registered" ;;
		106) echo "Illegal ME - barred by the carrier" ;;
		107) echo "GPRS services not allowed" ;;
		111) echo "PLMN not allowed" ;;
		112) echo "Location area not allowed" ;;
		113) echo "Roaming not allowed in this location area" ;;
		125) echo "Invalid transition ID" ;;
		126) echo "Call already cleared" ;;
		127) echo "User busy" ;;
		128) echo "No user responding" ;;
		129) echo "User alerting, no answer" ;;
		130) echo "Call rejected" ;;
		131) echo "Number changed" ;;
		132) echo "Service option not supported" ;;
		133) echo "Requested service option not subscribed" ;;
		134) echo "Service option temporarily out of order" ;;
		135) echo "Facility rejected" ;;
		136) echo "Response to STATUS ENQUIRY" ;;
		137) echo "Normal, unspecified" ;;
		138) echo "No circuit/channel available" ;;
		139) echo "Network out of order" ;;
		140) echo "Temporary failure" ;;
		141) echo "Switching equipment congestion" ;;
		142) echo "Access information discarded" ;;
		143) echo "Requested circuit/channel not available" ;;
		144) echo "Resources unavailable, unspecified" ;;
		145) echo "Quality of service unavailable" ;;
		146) echo "Requested facility not subscribed" ;;
		147) echo "Incoming calls barred within the CUG" ;;
		148) echo "Unspecified GPRS error" ;;
		149) echo "PDP authentication failure (check the APN login/password)" ;;
		150) echo "Invalid mobile class" ;;
		151) echo "Bearer service not implemented" ;;
		152) echo "Channel type not implemented" ;;
		153) echo "Requested facility not implemented" ;;
		154) echo "Only restricted digital information bearer capability is available" ;;
		155) echo "Service or option not implemented, unspecified" ;;
		156) echo "Invalid transaction identifier value" ;;
		157) echo "User not member of CUG" ;;
		158) echo "Incompatible destination" ;;
		159) echo "Invalid transit network selection" ;;
		160) echo "Semantically incorrect message" ;;
		161) echo "Invalid mandatory information" ;;
		162) echo "Message type non-existent or not implemented" ;;
		163) echo "Message type not compatible with protocol state" ;;
		164) echo "Information element non-existent or not implemented" ;;
		165) echo "Conditional IE error" ;;
		166) echo "Message not compatible with protocol state" ;;
		167) echo "Recovery on timer expiry" ;;
		168) echo "Protocol error, unspecified" ;;
		169) echo "Interworking, unspecified" ;;
		170) echo "Non-standard error" ;;
		171) echo "User determined user busy" ;;
		172) echo "User determined no user responding" ;;
		173) echo "User determined user alerting no answer" ;;
		174) echo "Call waiting service not activated" ;;
		175) echo "Supplementary services not supported" ;;
		200) echo "Unknown class" ;;
		201) echo "No phone book in the memory" ;;
		202) echo "Not support storing into the phone book" ;;
		203) echo "Phone book storage is full" ;;
		204) echo "The record number can not exceed the maximum record number" ;;
		205) echo "Invalid record number" ;;
		206) echo "The text is too long" ;;
		207) echo "Not support reading records by call type" ;;
		208) echo "Invalid phone book index" ;;
		209) echo "Fail to read phone book" ;;
		210) echo "Fail to write phone book" ;;
		211) echo "Fail to delete phone book" ;;
		212) echo "Fail to find a valid phone book record" ;;
		213) echo "Invalid phone book index" ;;
		214) echo "Phone book entry is being used" ;;
		256) echo "Operation temporary not allowed" ;;
		257) echo "Call barred" ;;
		258) echo "Phone is busy" ;;
		259) echo "User abort" ;;
		260) echo "Invalid dial string" ;;
		261) echo "SS not executed" ;;
		262) echo "SIM/USIM card error" ;;
		263) echo "Memory failure" ;;
		264) echo "Invalid parameter" ;;
		265) echo "FDN blocked" ;;
		266) echo "BDN blocked" ;;
		300) echo "ME failure" ;;
		301) echo "SMS service of ME reserved" ;;
		302) echo "Operation not allowed" ;;
		303) echo "Operation not supported" ;;
		304) echo "Invalid PDU mode parameter" ;;
		305) echo "Invalid text mode parameter" ;;
		310) echo "SIM not inserted" ;;
		311) echo "SIM PIN required" ;;
		312) echo "PH-SIM PIN required" ;;
		313) echo "SIM failure" ;;
		314) echo "SIM busy" ;;
		315) echo "SIM wrong" ;;
		316) echo "SIM PUK required" ;;
		317) echo "SIM PIN2 required" ;;
		318) echo "SIM PUK2 required" ;;
		320) echo "Memory failure" ;;
		321) echo "Invalid memory index" ;;
		322) echo "Memory full" ;;
		330) echo "SMSC address unknown" ;;
		331) echo "No network service" ;;
		332) echo "Network timeout" ;;
		340) echo "No CNMA acknowledgment expected" ;;
		500) echo "Unknown error" ;;
		512) echo "User abort" ;;
		513) echo "Unable to store" ;;
		514) echo "Invalid status" ;;
		515) echo "Device busy or invalid character in string" ;;
		516) echo "Invalid length" ;;
		517) echo "Invalid character in text string" ;;
		518) echo "Invalid parameter" ;;
		519) echo "Invalid length or character" ;;
		520) echo "Invalid character in password" ;;
		521) echo "Device busy" ;;
		522) echo "Device busy" ;;
		526) echo "Invalid parameter" ;;
		527) echo "Invalid block" ;;
		528) echo "SIM condition is not satisfied" ;;
		529) echo "PIN blocked" ;;
		530) echo "PIN blocked" ;;
		531) echo "Invalid parameter" ;;
		532) echo "Device busy" ;;
		533) echo "Invalid parameter" ;;
		534) echo "Invalid character" ;;
		535) echo "Invalid parameter" ;;
		536) echo "Wrong state" ;;
		537) echo "Invalid character in dial string" ;;
		538) echo "Invalid parameter" ;;
		672) echo "SIM powered down" ;;
		*) return 1 ;;
	esac
}
